@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "",
  "password": "",
  "email": "",
  "avatarColor": "",
  "avatarImage": "<add-a-base64-encoded-string>"
}
