@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/images/<userId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
### "image": "<base64-encoded-string>"
POST {{baseUrl}}/{{urlPath}}/images/profile
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "image": "https://res.cloudinary.com/dtnfoho5x/image/upload/v1664719522/63399aa1c5fcc2154ba26c47.png"
}

###
POST {{baseUrl}}/{{urlPath}}/images/background
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, image value is either
# - a base64 encoded string for a new image or
# - an already existing cloudinary image url

{
  "image": "https://res.cloudinary.com/dtnfoho5x/image/upload/v1664719522/63399aa1c5fcc2154ba26c47.png"
}

###
DELETE {{baseUrl}}/{{urlPath}}/images/633ae3fcaa4f05bce491a157
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/images/background/63399aa1c5fcc2154ba26c47
Content-Type: application/json
Accept: application/json
withCredentials: true
